name: Favorey
favicon: null
layout_spectrum: 0.3692313013598323
typography_spectrum: 0.17129571386612952
title: Favorey Network
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff6319'
    - '#a59c95'
    - '#ffaa88'
    - '#ff8551'
  brandStrength: 0.5534342059399933
  lightness: 0.22812943113967776
  saturation: 0.13596884696744382
  rhythmicContrast: 0.34602408157661557
purpose: []
